[phases.setup]
nixPkgs = [
  "nodejs_22"
  "pnpm"
  "python3"
  "gcc"
  "gnumake"
  "pkg-config"
  "glibc"
]

[phases.install]
cmds = [
  "pnpm install --unsafe-perm",
  "pnpm rebuild"
]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
dependsOn = ["build"]
cmds = ["pnpm start"]
