[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --unsafe-perm --no-optional"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
dependsOn = ["build"]
cmds = ["pnpm start"]
