[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["chmod +x build.sh && bash build.sh"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
cmds = ["pnpm start"]
dependsOn = ["build"]