[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["pnpm install --shamefully-hoist"]

[phases.build]
cmds = ["pnpm build"]

[phases.start]
cmds = ["pnpm start"]
dependsOn = ["build"]