# ==============================================
# MATRIX PROTOCOL WEBSITE - DOCKER COMPOSE
# ==============================================
# Production-ready Docker Compose configuration
# Compatible with Coolify deployment platform

version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    
    ports:
      - "${PORT:-3000}:3000"
    
    environment:
      # Application settings
      - NODE_ENV=production
      - NUXT_PUBLIC_APP_NAME=${NUXT_PUBLIC_APP_NAME:-Matrix Protocol}
      - NUXT_PUBLIC_APP_VERSION=${NUXT_PUBLIC_APP_VERSION:-1.0.0}
      - NUXT_PUBLIC_APP_URL=${NUXT_PUBLIC_APP_URL:-http://localhost:3000}
      
      # External links
      - NUXT_PUBLIC_GITHUB_URL=${NUXT_PUBLIC_GITHUB_URL:-https://github.com/matrix-protocol/matrix-protocol}
      - NUXT_PUBLIC_DISCORD_URL=${NUXT_PUBLIC_DISCORD_URL:-}
      - NUXT_PUBLIC_DISCUSSIONS_URL=${NUXT_PUBLIC_DISCUSSIONS_URL:-}
      - NUXT_PUBLIC_DOCS_URL=${NUXT_PUBLIC_DOCS_URL:-}
      
      # API configuration
      - NUXT_PUBLIC_API_BASE_URL=${NUXT_PUBLIC_API_BASE_URL:-http://localhost:4000}
      - NUXT_API_SECRET=${NUXT_API_SECRET}
      
      # Analytics (optional)
      - NUXT_PUBLIC_PLAUSIBLE_DOMAIN=${NUXT_PUBLIC_PLAUSIBLE_DOMAIN:-}
      - NUXT_PUBLIC_GA_ID=${NUXT_PUBLIC_GA_ID:-}
      
      # Development settings
      - NUXT_DEVTOOLS=${NUXT_DEVTOOLS:-false}
      - NUXT_TELEMETRY_DISABLED=${NUXT_TELEMETRY_DISABLED:-true}
    
    # Use environment file if available
    env_file:
      - .env
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {r.statusCode === 200 ? process.exit(0) : process.exit(1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Security
    security_opt:
      - no-new-privileges:true
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ==============================================
# VOLUMES (if needed in the future)
# ==============================================
volumes:
  app_data:
    driver: local

# ==============================================
# NETWORKS (if needed for multi-service setup)
# ==============================================
networks:
  default:
    driver: bridge