name: Weekly Sync Check

on:
  schedule:
    # Every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      force_check:
        description: 'Force comprehensive sync check'
        required: false
        default: false
        type: boolean

jobs:
  comprehensive-sync:
    name: Weekly Repository-Website Sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        path: repository
        
    - name: Checkout website repository  
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/matrix-protocol-website
        path: website
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run comprehensive sync check
      working-directory: repository
      run: |
        # Make scripts executable
        chmod +x scripts/check-sync.sh scripts/check-versions.sh
        
        echo "🔍 Running weekly synchronization check..."
        
        # Run version check first
        echo "📋 Checking versions..."
        ./scripts/check-versions.sh
        version_status=$?
        
        # Run sync check
        echo "🔄 Checking synchronization..."
        WEBSITE_PATH="../website" ./scripts/check-sync.sh
        sync_status=$?
        
        # Generate detailed report
        echo "📊 Generating weekly report..."
        
        cat > sync-report.md << 'EOF'
        # Weekly Synchronization Report
        
        **Date**: $(date -u +"%Y-%m-%d %H:%M UTC")
        **Trigger**: Weekly automatic verification
        
        ## Verification Status
        
        ### ✅ Version Check
        EOF
        
        if [ $version_status -eq 0 ]; then
          echo "- Status: ✅ SUCCESS" >> sync-report.md
          echo "- All versions are at v0.0.1-beta" >> sync-report.md
        else
          echo "- Status: ❌ FAILED" >> sync-report.md
          echo "- Version problems detected" >> sync-report.md
        fi
        
        cat >> sync-report.md << 'EOF'
        
        ### 🔄 Synchronization Check
        EOF
        
        if [ $sync_status -eq 0 ]; then
          echo "- Status: ✅ SUCCESS" >> sync-report.md
          echo "- Repository and website are synchronized" >> sync-report.md
        else
          echo "- Status: ❌ FAILED" >> sync-report.md
          echo "- Divergences detected between repository and website" >> sync-report.md
        fi
        
        cat >> sync-report.md << 'EOF'
        
        ## Next Steps
        
        EOF
        
        if [ $version_status -ne 0 ] || [ $sync_status -ne 0 ]; then
          cat >> sync-report.md << 'EOF'
        - [ ] Review detailed execution logs
        - [ ] Consult [SYNC_GUIDE.md](./SYNC_GUIDE.md)
        - [ ] Apply necessary corrections
        - [ ] Execute manual validation
        EOF
        else
          echo "- ✅ No action necessary - everything synchronized!" >> sync-report.md
        fi
        
        cat sync-report.md
        
        # Exit with error if any check failed
        if [ $version_status -ne 0 ] || [ $sync_status -ne 0 ]; then
          exit 1
        fi
        
    - name: Upload sync report
      uses: actions/upload-artifact@v4
      with:
        name: weekly-sync-report
        path: repository/sync-report.md
        retention-days: 30
        
    - name: Create issue on sync failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          let reportContent = '';
          try {
            reportContent = fs.readFileSync('repository/sync-report.md', 'utf8');
          } catch (error) {
            reportContent = 'Report could not be generated due to script failure.';
          }
          
          const title = `[SYNC] Weekly Report - Divergences Detected (${new Date().toISOString().split('T')[0]})`;
          const body = `
          ## 🚨 Weekly Check - Problems Detected
          
          The weekly automatic verification detected synchronization problems.
          
          **Trigger**: Weekly verification (every Monday)
          **Date**: ${new Date().toISOString()}
          **Workflow**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          ## Detailed Report
          
          ${reportContent}
          
          ## Required Actions
          
          1. **Review logs**: Check details in workflow execution
          2. **Execute locally**: \`./scripts/check-sync.sh\` and \`./scripts/check-versions.sh\`
          3. **Consult documentation**: [SYNC_GUIDE.md](./SYNC_GUIDE.md)
          4. **Apply corrections**: Follow documented procedures
          5. **Close issue**: After complete resolution
          
          ---
          
          **Automation**: This issue was created automatically by the CI/CD system.
          **Labels**: sync-required, weekly-check, automated
          `;
          
          const issue = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['sync-required', 'weekly-check', 'automated']
          });
          
          console.log(`Issue created: ${issue.data.html_url}`);
          
    - name: Comment on success
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          console.log('✅ Weekly verification completed successfully!');
          console.log('📊 Repository and website are synchronized');
          console.log('🎉 No action necessary');

  metrics-collection:
    name: Collect Sync Metrics
    runs-on: ubuntu-latest
    if: always()
    needs: comprehensive-sync
    
    steps:
    - name: Collect metrics
      run: |
        echo "📈 Collecting synchronization metrics..."
        
        # This could be expanded to send metrics to monitoring systems
        echo "Timestamp: $(date -u +"%Y-%m-%d %H:%M UTC")"
        echo "Status: ${{ needs.comprehensive-sync.result }}"
        echo "Repository: ${{ github.repository }}"
        echo "Workflow: ${{ github.workflow }}"
        
        # Add to GitHub summary
        echo "## 📊 Weekly Verification Metrics" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date -u +"%Y-%m-%d %H:%M UTC")" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ needs.comprehensive-sync.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY