name: Content Validation

on:
  pull_request:
    paths:
      - '../../content/**'
      - '../../scripts/**'
      - '../../docs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: website
      - name: Run content audit
        run: node website/scripts/content-audit.js
      - name: Run validation automation
        run: node website/scripts/validation-automation.js
      - name: Enforce Quality Gates
        run: |
          node -e "const fs=require('fs');const p='website/docs/dynamic-navigation/qa-quality-gates.json';const d=JSON.parse(fs.readFileSync(p,'utf8'));if(d.status!=='PASSED'){console.error('Quality Gates failed');process.exit(1)} else {console.log('Quality Gates PASSED')}"